# ================
# DATASOURCE CONFIG
# ================
spring.datasource.url=jdbc:postgresql://${DB_HOST:ep-calm-union-a7q0ojm7-pooler.ap-southeast-2.aws.neon.tech}:${DB_PORT:5432}/${DB_NAME:rent_management}?sslmode=require&channel_binding=require
spring.datasource.username=${DB_USERNAME:neondb_owner}
spring.datasource.password=${DB_PASSWORD:npg_iLbkw4gz2KST}

# ================
# JPA CONFIG
# ================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# ================
# FLYWAY CONFIG
# ================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

# ================
# SERVER CONFIG
# ================
server.port=8080